on:
  workflow_call:
    inputs:
      codeql-execution:
        required: true
        type: boolean
        default: false
      sbom-generation:
        required: true
        type: boolean
        default: false
      target-project-path:
        required: false
        type: string
        default: ''
      sbom-filename:
        required: false
        type: string
        default: ''

jobs:
  security-scan:
    name: 'Scan solution'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Initialize CodeQL
        if: ${{ inputs.codeql-execution == true }}
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'
          build-mode: autobuild

      - name: Perform CodeQL Analysis
        if: ${{ inputs.codeql-execution == true }}
        uses: github/codeql-action/analyze@v2
 
      - name: Generate JSON SBOM
        if: ${{ inputs.sbom-generation == true && inputs.target-project-path != '' && inputs.sbom-filename != '' }}
        run: |
          dotnet tool update --global CycloneDX
          dotnet-CycloneDX ${{ inputs.target-project-path }} --output-format json --exclude-test-projects --recursive --output ${{ github.workspace }}/artifacts/sboms --filename ${{ inputs.sbom-filename }}
       
      - name: Upload Generated SBOM File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.sbom-filename }}
          path: ${{ github.workspace }}/artifacts/sboms/${{ inputs.sbom-filename }}
          retention-days: 5