on:
  workflow_call:
    inputs:
      codeql-execution:
        required: true
        type: boolean
        default: false

jobs:
  security-scan:
    name: 'Scan solution'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Initialize CodeQL
        if: ${{ inputs.codeql-execution == true }}
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'
          build-mode: autobuild

      - name: Perform CodeQL Analysis
        if: ${{ inputs.codeql-execution == true }}
        uses: github/codeql-action/analyze@v2